config/routes.rb
Finance::Application.routes.draw do
  #match 'site/:id' => 'catalog#view'
  resources :watches

  match '/auth/github/callback' => 'site#login'
  match '/logout' => 'site#logout'

  root :to => 'site#index'
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  has_many :watch_matches
  has_many :watches, :through => :watch_matches
  validates :pid, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :watches
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  belongs_to :user
  has_many :watch_matches
  has_many :petitions, :through => :watch_matches, :order => "signatures desc"
  validates :term, :length => { :minimum => 3 }

  def find_matches
    if last_check
      checkp = Petition.where("created_time > ?", last_check)
    else
      checkp = Petition.all
    end

    # get a list of pids we've already matched
    pids = {}
    petitions.each { |p| pids[p.pid] = true }

    matches = []
    checkp.each do |pet|
      next if pids[pet.pid]
      pattern = Regexp.new(term)
      match = false
      if pattern =~ pet.title
        match = :title
      elsif pattern =~ pet.body
        match = :body
      elsif pattern =~ pet.issues
        match = :issues
      end

      if match
        petitions << pet
        matches << pet
      end
    end

    latest_date = Petition.maximum('created_time')
    last_check = latest_date
    save

    matches
  end
end

app/models/watch_match.rb
class WatchMatch < ActiveRecord::Base
  belongs_to :watch
  belongs_to :petition
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_user

  def require_login
    if !current_user
      redirect_to '/' and return
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def login
    data = env["omniauth.auth"]
    p data['info']
    email = data['info'].email
    login = data['info'].nickname
    if login
      user = User.find_or_create_by_login(login)
      user.email = email
      user.save
      session[:user_id] = user.id
    end
    redirect_to '/watches'
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_filter :require_login

  # GET /watches
  # GET /watches.json
  def index
    @watches = current_user.watches

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @watches }
    end
  end

  # GET /watches/1
  # GET /watches/1.json
  def show
    @watch = current_user.watches.find(params[:id])
    @petitions = @watch.petitions

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @watch }
    end
  end

  # GET /watches/new
  # GET /watches/new.json
  def new
    @watch = Watch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @watch }
    end
  end

  # POST /watches
  # POST /watches.json
  def create
    @watch = Watch.new(params[:watch])
    @watch.user = current_user
    respond_to do |format|
      if @watch.save
        @watch.find_matches
        format.html { redirect_to @watch, notice: 'Here are your results.  Any future matches will be emailed to you.' }
        format.json { render json: @watch, status: :created, location: @watch }
      else
        format.html { render action: "new" }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watches/1
  # DELETE /watches/1.json
  def destroy
    @watch = current_user.watches.find(params[:id])
    @watch.destroy

    respond_to do |format|
      format.html { redirect_to watches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
require 'digest/md5'

module ApplicationHelper
  def gravatar
    email = @current_user.email.downcase
    hash = Digest::MD5.hexdigest(email)
    image_src = "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Petition Watch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <% if @current_user %>
            <li><a href="/">Home</a></li>
            <li><a href="/watches">Watches</a></li>
            <li><a href="/logout">Logout</a></li>
            <li> &nbsp; &nbsp; </li>
            <li class="user">
              <img src="<%= gravatar %>?s=40">
            </li>
          <% else %>
            <li><a href="/auth/github">Login with GitHub</a></li>
          <% end %>
        </ul>
        <h3 class="muted">Petition Watch</h3>
      </div>

      <hr>

      <%= yield %>

      <hr>

    </div> <!-- /container -->
  </body>
</html>

app/views/site/index.html.erb
<div class="jumbotron">
  <h1>Get Petition Alerts</h1>
  <p class="lead">If you want to participate in letting the White House know what you care about, tell us and we'll keep an eye on the petitions for you so you can participate in anything that concerns you.</p>
  <% if @current_user %>
    <a class="btn btn-large btn-success" href="/watches/new">Set your petition alerts now</a>
  <% else %>
    <a class="btn btn-large btn-success" href="/auth/github">Set your petition alerts now</a>
  <% end %>

  <img src="/seal.png">

</div>

app/views/watches/_form.html.erb
<%= form_for @watch, :html => { :class => "form-horizontal" } do |f| %>
  <% if @watch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
      <% @watch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="term">Watch String</label>
    <div class="controls">
      <%= f.text_field :term %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Create Watch</button>
    </div>
  </div>

<% end %>

app/views/watches/edit.html.erb
<h1>Edit Your Watch</h1>

<%= render 'form' %>

<%= link_to 'Show', @watch %> |
<%= link_to 'Back', watches_path %>

app/views/watches/index.html.erb
<div class="create-watch">
    <a class="btn btn-success" href="/watches/new">Create a New Watch</a>
</div>

<% if @watches.count == 0 %>
  <h1>You Have No Watches</h1>
<% else %>
  <h1>My Watches</h1>

  <div class="row-fluid marketing">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Search Term</th>
            <th>Matches</th>
          </tr>
        </thead>
        <tbody>
        <% @watches.each do |watch| %>
          <tr>
            <td>
              <%= link_to 'x', watch_path(watch), :confirm => 'Are you sure?', :method => :delete %>

            <td><%= watch.term %></td>
            <td><a href="/watches/<%= watch.id %>"><%= watch.petitions.count %> matches</a></td>
            <td>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
<% end %>

app/views/watches/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', watches_path %>

app/views/watches/show.html.erb
<p class="text-success"><%= notice %></p>

<% if @petitions.size == 0 %>
  <h1>No Petitions</h1>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Signatures</th>
        <th>Response</th>
      </tr>
    </thead>
    <tbody>
    <% @petitions.each do |p| %>
      <tr>
        <td>
          <a href="<%= p.url %>"><%= p.title[0, 50] %></a>
        </td>
        <td><%= p.signatures %></td>
        <td>
          <% if p.answered %>
            <span class="text-success">Answered</p>
          <% end %>
        </td>
      </tr>
      </div>
    <% end %>
  </tbody>
  </table>
<% end %>

<%= link_to 'Back', watches_path %>